### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by fatahn** [ezhlobo/babel-plugin-transform-jsx-classname-components#2]
Jests tests fail:
```
import { Icons } from '@mattermarkstudios/aet-components'
IconBlock
      39 |         Icons.Arrow(aria-hidden scale=0.7)
    > 40 |
      41 |     div
      42 |       ButtonWrapper
```
`ReferenceError: Icons is not defined`

**Comment by ezhlobo** [comment]
@fatahn if you are talking about jest, then make sure that jest configured with babel-jest transpiler and respect your babelrc file.

Otherwise, could you please give more details, so I'll be able to reproduce the bug and figure it out.
